jellyfin-beta:
image: jellyfin/jellyfin:unstable # Uses the bleeding-edge development image
container_name: jellyfin-beta
restart: unless-stopped

environment:
  - PUID=1000             # Change this to your user's UID (id -u)
  - PGID=1000             # Change this to your user's GID (id -g)
  - TZ=America/New_York   # Change to your timezone (e.g., Europe/London)

# Map device for Intel QuickSync/VAAPI hardware transcoding
devices:
  - /dev/dri:/dev/dri
  
# Add container to the host's render group for GPU access
group_add:
  - "109" # !!! IMPORTANT: Replace "109" with the GID of your 'render' or 'video' group on your host !!!

ports:
  - 8096:8096/tcp   # 
  - 8920:8920/tcp   # HTTPS 
  - 7359:7359/udp   # Discovery 
  - 1900:1900/udp   # DLNA 
# Volume mappings - Uses separate config/cache volumes but can share media
volumes:
  - /DATA/AppData/jellyfin/config:/config # SEPARATE Configuration files
  - /media/ZimaOS-HD/Media/Movies:movies  # Shared media library (Read-only)
  - /media/ZimaOS-HD/Media/TV Shows:tvshows # Shared media library (Read-only)
